### PR TITLE
Replace wrench with chmodr

### PR DESCRIPTION
**Pull request by JordanKnott**
Wrench is now considered deprecated so switch to the chmodr library
for handling file permissions.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hi @JordanKnott, I am not actively maintaining this anymore, but am willing to help steward PR's and what not for people who are.  In this case, it seems reasonable, but is not following the existing formatting/style conventions.  If you get it consistent, I am willing to merge and run a test and publish.

If you are using this, and want to actively contribute then I would be happy to add you as a contributor once I trust that you will be a contentious maintainer :)

**Comment by JordanKnott** [comment]
@wesleytodd I've fixed the formatting, how does it look now?

I'm definitely interested in actively contributing, any ideas on what could be worked on?

**Comment by JordanKnott** [comment]
As a side note, this commit solves issue #191 (it's marked closed but was never actually resolved)

**Comment by JordanKnott** [comment]
@wesleytodd Are there any other style changes that need to be done?

**Comment by wesleytodd** [comment]
Hey, sorry I have been busy with work and life lately.  I will try to look at these tonight.  If everything looks good I will not only merge and publish but add you (@JordanKnott) as a contributor so you don't need to wait on me in the future.  Sorry for the delay.

**Comment by JordanKnott** [comment]
@alextegelid Since it seems like it might be awhile until this gets merged, one option would be to use the `npm link` command and install the package using my fork. I don't know of any other way through npm to patch though :smile:

**Comment by alextegelid** [comment]
I've manually (and painfully) set up the installation that led me to this issue in the first place. If this isn't merged by the time I'll set up my next project I'll look into `npm link`. Thanks for the tip!

**Comment by JordanKnott** [comment]
@wesleytodd Any progress on merging this into master or does it still need some more work?

**Comment by strafe-creative** [comment]
Can someone please merge this?

**Comment by JordanKnott** [comment]
@wesleytodd I'm still watching this PR so if any changes need to be done before it can be merged, let me know. It seems like this PR would help a few people.

**Comment by manel** [comment]
@JordanKnott I've applied your changes to my local generator and it worked perfectly. Thanks for fixing it.
@wesleytodd is it possible to merge this PR, please?

**Comment by JordanKnott** [comment]
@manel Happy it helped someone! I don't think it's going to be merged into master anytime soon though....

**Comment by vburlak** [comment]
Have the same issue. @wesleytodd any way to merge this? 
Thanks!

**Comment by wesleytodd** [comment]
I added @JordanKnott in the past as a contributor, maybe they moved on from this?  My guess is this probably shouldn't be used anymore, but I am so far removed from this ecosystem that I dont know if there is anything to replace it with.  Sorry!

**Comment by JordanKnott** [comment]
@wesleytodd Odd, I never saw that I was added a contributor. I'm still watching this pull request though I don't actually use this tool anymore.

**Comment by JordanKnott** [comment]
@wesleytodd I just checked, I'm not able to merge pull requests.

**Comment by wesleytodd** [comment]
Oops! I read my comment above and thought I had done it.  You are added now!

**Pull request merged**
