### PR TITLE
Merge bugfix & bump version

### PR DESCRIPTION
**Pull request by JordanKnott**

### CODE REVIEW

**Comment by JordanKnott** [comment]
@wesleytodd I've merged the PR and increased the bugfix package version however I do not have access to publish the change the NPM. Could you do that?

**Comment by wesleytodd** [comment]
Sure! It also looks like committing on this project triggered a bunch of dependabot things.  Want to take a look at those PR's and see which of them make sense to merge before any publish?

**Comment by JordanKnott** [comment]
I'm not sure when I can look at the dependency updates, so I would say go ahead and publish now so the bugfix is at least available.

**Comment by BriceN** [comment]
Yes please do that ! I really need that bugfix and I don't know how to install this package manually :/

**Comment by BriceN** [comment]
I manage to do it with sudo npm install -g https://github.com/wesleytodd/YeoPress/tarball/master

**Comment by wesleytodd** [comment]
Hey, what is your npm user @JordanKnott? So that I can give you publish rights.  I looked for `JordanKnott` and it didn't have any user.

**Comment by JordanKnott** [comment]
@wesleytodd It's `jordanthedev`

**Comment by wesleytodd** [comment]
Ok, I added you.  You will need to enable 2fa on your account to publish.  Let me know if you have any issues.

**Comment by brice-noowu** [comment]
Thank you guys !

**Pull request merged**
